name: Media
description: |
  Media downloader / manager
version: 1.0.0
category: Media
maintainer: Magnus Ullberg <magnus@ullberg.us>
license: Apache 2.0
projectURL: https://github.com/ullbergm/rancher-catalog
