.catalog:
  name: Media Manager
  version: 1.0.0
  description: Media manager
  uuid: media-0
  questions:
    - variable: "CONFIG_DIR"
      label: "Configuration location"
      description: |
        The local folder on the host to store the configuration in.
        Each application will be stored in a subfolder of this one.
      type: "string"
      default: "/data/config"
      required: true
    - variable: "DOWNLOAD_DIR"
      label: "Download location"
      description: |
        The local folder on the host to store the downloaded files before they are processed.
      type: "string"
      default: "/data/downloads"
      required: true
    - variable: "PGID"
      label: "GID"
      description: |
        The GID to run the tools with.
      type: "int"
      default: 0
      min: 1
      max: 65535
      required: true
    - variable: "PUID"
      label: "UID"
      description: |
        The UID to run the tools with.
      type: "int"
      default: 0
      min: 1
      max: 65535
      required: true
    - variable: "TZ"
      label: "Timezone"
      description: |
        The timezone you want to use.
      type: "string"
      default: "America/New_York"
      required: true
    - variable: "VPN_LAN_NETWORK"
      label: "LAN Network range"
      description: |
        The LAN network range.
      type: "string"
      default: "192.168.0.0/16"
      required: true
    - variable: "VPN_NAME_SERVERS"
      label: "VPN Name Servers"
      description: |
        The nameservers you want to use for the VPN.
      type: "string"
      default: "8.8.8.8, 8.8.4.4"
      required: true
    - variable: "VPN_STRICT_PORT_FORWARD"
      label: "VPN Strict Port Forward"
      description: |
        Enable Strict Port Forward for the VPN.
      type: "boolean"
      default: "true"
      required: true
    - variable: "VPN_USER"
      label: "VPN Username"
      description: |
        The VPN username you want to use.
      type: "string"
      default: ""
      required: true
    - variable: "VPN_PASS"
      label: "VPN Password"
      description: |
        The password for the VPN.
      type: "string"
      default: ""
      required: true
    - variable: "VPN_PROV"
      label: "VPN Provider"
      description: |
        The VPN provider you want to use.
      type: "string"
      default: "pia"
      required: true
    - variable: "VPN_REMOTE"
      label: "VPN Remote"
      description: |
        The VPN remote host you want to use.
      type: "string"
      default: ""
      required: true
services:
  frontend:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - hostname: "sonarr.${DOMAIN}"
        path: ''
        priority: 1
        protocol: http
        service: sonarr
        source_port: 80
        target_port: 8989
      - hostname: "radarr.${DOMAIN}"
        path: ''
        priority: 2
        protocol: http
        service: radarr
        source_port: 80
        target_port: 7878
      - hostname: "nzbhydra.${DOMAIN}"
        path: ''
        priority: 3
        protocol: http
        service: nzbhydra
        source_port: 80
        target_port: 80
      - hostname: "nzbget.${DOMAIN}"
        path: ''
        priority: 4
        protocol: http
        service: nzbget
        source_port: 80
        target_port: 6789
      - hostname: "mylar.${DOMAIN}"
        path: ''
        priority: 5
        protocol: http
        service: mylar
        source_port: 80
        target_port: 8090
      - hostname: "lazylibrarian.${DOMAIN}"
        path: ''
        priority: 6
        protocol: http
        service: lazylibrarian
        source_port: 80
        target_port: 5299
      - hostname: "headphones.${DOMAIN}"
        path: ''
        priority: 7
        protocol: http
        service: headphones
        source_port: 80
        target_port: 8181
      - hostname: "emby.${DOMAIN}"
        path: ''
        priority: 8
        protocol: http
        service: embyserver
        source_port: 80
        target_port: 8096
      - hostname: "smokeping.${DOMAIN}"
        path: ''
        priority: 9
        protocol: http
        service: smokeping
        source_port: 80
        target_port: 80
      - hostname: "deluge.${DOMAIN}"
        path: ''
        priority: 10
        protocol: http
        service: deluge
        source_port: 80
        target_port: 8112
      - hostname: "booksonic.${DOMAIN}"
        path: ''
        priority: 11
        protocol: http
        service: booksonic
        source_port: 80
        target_port: 4040
      - hostname: "ubooquity.${DOMAIN}"
        path: ''
        priority: 12
        protocol: http
        service: ubooquity
        source_port: 80
        target_port: 2202
      - hostname: "ubooquity-admin.${DOMAIN}"
        path: ''
        priority: 13
        protocol: http
        service: ubooquity
        source_port: 80
        target_port: 2203
      - hostname: ''
        path: ''
        priority: 14
        protocol: http
        service: organizr
        source_port: 80
        target_port: 80
