.catalog:
  name: Media Manager
  version: 1.0.0
  description: Media manager
  uuid: media-0
  questions:
  - variable: "CONFIG_DIR"
      label: "Configuration location"
      description: |
        The local folder on the host to store the configuration in.
        Each application will be stored in a subfolder of this one.
      type: "string"
      default: "/data/config"
      required: true
  - variable: "DOWNLOAD_DIR"
      label: "Download location"
      description: |
        The local folder on the host to store the downloaded files before they are processed.
      type: "string"
      default: "/data/downloads"
      required: true
  - variable: "PGID"
      label: "GID"
      description: |
        The GID to run the tools with.
      type: "int"
      default: 0
      min: 1
      max: 65535
      required: true
  - variable: "PUID"
      label: "UID"
      description: |
        The UID to run the tools with.
      type: "int"
      default: 0
      min: 1
      max: 65535
      required: true
  - variable: "TZ"
      label: "Timezone"
      description: |
        The timezone you want to use.
      type: "string"
      default: "America/New_York"
      required: true
  - variable: "VPN_LAN_NETWORK"
      label: "LAN Network range"
      description: |
        The LAN network range.
      type: "string"
      default: "192.168.0.0/16"
      required: true
  - variable: "VPN_NAME_SERVERS"
      label: "VPN Name Servers"
      description: |
        The nameservers you want to use for the VPN.
      type: "string"
      default: "8.8.8.8, 8.8.4.4"
      required: true
  - variable: "VPN_STRICT_PORT_FORWARD"
      label: "VPN Strict Port Forward"
      description: |
        Enable Strict Port Forward for the VPN.
      type: "boolean"
      default: "true"
      required: true
  - variable: "VPN_USER"
      label: "VPN Username"
      description: |
        The VPN username you want to use.
      type: "string"
      default: ""
      required: true
  - variable: "VPN_PASS"
      label: "VPN Password"
      description: |
        The password for the VPN.
      type: "string"
      default: ""
      required: true
  - variable: "VPN_PROV"
      label: "VPN Provider"
      description: |
        The VPN provider you want to use.
      type: "string"
      default: "pia"
      required: true
  - variable: "VPN_REMOTE"
      label: "VPN Remote"
      description: |
        The VPN remote host you want to use.
      type: "string"
      default: ""
      required: true
